name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.query.outputs.linux }}
      u-boot: ${{ steps.query.outputs.u-boot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Query available board configs
        id: query
        run: |
          echo "linux=$(./bsp --json edition linux)" >> $GITHUB_OUTPUT
          echo "u-boot=$(./bsp --json edition u-boot)" >> $GITHUB_OUTPUT
  build_u-boot:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        u-boot: ${{fromJSON(needs.query.outputs.u-boot)}}
    steps:
      - name: Build
        uses: opsiff/bsp@main
        with:
          target: u-boot
          edition: ${{ matrix.u-boot }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-${{ matrix.u-boot }}
          path: .output
  build_linux:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: ${{fromJSON(needs.query.outputs.linux)}}
    steps:
      - name: Build
        uses: opsiff/bsp@main
        with:
          target: linux
          edition: ${{ matrix.linux }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.linux }}
          path: .output
  
